DexHeaderFormatAnalyzer: do not fail when several methods refer to the same metadata
Some Android applications use the same class annotations metadata
structure for several annotations. This makes `processClassAnnotations()`
create a structure twice at the same location. As `setItem.toDataType()`
always creates a new structure which is not "compatible" with any
existing one, `createData()` fails:

    Could not create Data at address 007f35f8
    java.lang.RuntimeException: Could not create Data at address 007f35f8
            at ghidra.file.analyzers.FileFormatAnalyzer.createData(FileFormatAnalyzer.java:211)
            at ghidra.file.formats.android.dex.analyzer.DexHeaderFormatAnalyzer.processClassAnnotations(DexHeaderFormatAnalyzer.java:640)
            at ghidra.file.formats.android.dex.analyzer.DexHeaderFormatAnalyzer.processClassDefs(DexHeaderFormatAnalyzer.java:373)
            at ghidra.file.formats.android.dex.analyzer.DexHeaderFormatAnalyzer.analyze(DexHeaderFormatAnalyzer.java:76)
            at ghidra.file.analyzers.FileFormatAnalyzer.added(FileFormatAnalyzer.java:52)
            at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
            at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
            at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
            at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
            at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
            at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
            at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
            at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
            at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:315)
            at java.base/java.lang.Thread.run(Thread.java:829)

Fix this by only creating data if there is no defined data already.