fix(MIPS): split breakcode into high/low fields
Refactor the SLEIGH definition for the MIPS `break` instruction to handle split 10-bit code fields (bits 6-15 and 16-25) instead of a single 20-bit block. This change aligns Ghidra's MIPS model with the behavior of modern toolchains that enforce 10-bit limits on operands of the `break` instruction. For example, the MIPS LLVM backend in Clang throws an error when an operand exceeds 10 bits:

```
michael@laptop:~/Documents$ clang --target=mips-linux-gnu main.c -o program
main.c:2:6: error: expected 10-bit unsigned immediate
    2 |         asm("break 0, 0x400");
```

Similarly, the GNU C Cross-Compiler for MIPS throws an error if an operand exceeds the 10-bit limit:

```
michael@laptop:~/Documents$ mips-linux-gnu-gcc main.c -o program
/tmp/ccegYvhZ.s: Assembler messages:
/tmp/ccegYvhZ.s:25: Error: operand 1 out of range `break 0x400,0'
```